parameters:
#    zhvillues_database_test.example.class: Zhvillues\DatabaseTestBundle\Example

services:
#    zhvillues_database_test.example:
#        class: %zhvillues_database_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
